services:
  certbot:
    image: certbot/certbot:v2.11.0
    profiles: ["certbot"]
    restart: unless-stopped
    command: ["sh", "-c", "trap exit TERM; while :; do sleep 12h; done"]
    volumes:
      - /srv/data/{{ENV}}/certbot:/etc/letsencrypt
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app_net
